services:
  - type: web
    name: iot-gateway
    env: python
    plan: free
    rootDir: .
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MQTT_BROKER
        sync: false
      - key: MQTT_PORT
        value: "1883"
      - key: BACKEND_BASE
        sync: false
